function Xk = LittleF(Abiaspri,Axpri,B,C,D,E,Iz,Mv,Psipri,Rbiaspri,Ts,Vxpri,Vypri,a,b,delta,rpri)
%LittleF
%    Xk = LittleF(Abiaspri,Axpri,B,C,D,E,Iz,Mv,Psipri,Rbiaspri,Ts,Vxpri,Vypri,A,b,DELTA,RPRI)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    09-Jul-2026 14:02:45

t2 = cos(delta);
t3 = 1.0./Vxpri;
t4 = -rpri;
t5 = Rbiaspri+t4;
t6 = a.*t5;
t7 = b.*t5;
t8 = -t6;
t9 = Vypri+t7;
t10 = Vypri+t8;
t11 = t3.*t9;
t12 = atan(t11);
t13 = t3.*t10;
t14 = B.*t12;
t15 = atan(t13);
t16 = atan(t14);
t18 = delta+t15;
t19 = B.*t18;
t23 = -E.*(t14-t16);
t20 = atan(t19);
t26 = t14+t23;
t25 = -E.*(t19-t20);
t27 = atan(t26);
t28 = C.*t27;
t30 = t19+t25;
t29 = sin(t28);
t31 = atan(t30);
t32 = C.*t31;
t33 = sin(t32);
Xk = [Vypri+Ts.*((D.*t29+D.*t2.*t33)./Mv-Vxpri.*rpri);Vxpri+Ts.*(Abiaspri+Axpri+Vypri.*t4);rpri-(Ts.*(D.*b.*t29-D.*a.*t2.*t33))./Iz;Psipri+Ts.*rpri;Abiaspri+Axpri;Rbiaspri;Abiaspri];
end
