function Xk = LittleF(Abiaspri,Axpri,B,C,D,E,Iz,Mv,Psipri,Rbiaspri,Ts,Vxpri,Vypri,a,b,delta,rpri)
%LittleF
%    Xk = LittleF(Abiaspri,Axpri,B,C,D,E,Iz,Mv,Psipri,Rbiaspri,Ts,Vxpri,Vypri,A,b,DELTA,RPRI)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    06-Jul-2026 15:51:45

t2 = cos(delta);
t3 = Rbiaspri+rpri;
t4 = 1.0./Vxpri;
t5 = a.*t3;
t6 = b.*t3;
t7 = Vypri+t6;
t8 = -t5;
t9 = Vypri+t8;
t10 = t4.*t7;
t11 = atan(t10);
t12 = t4.*t9;
t13 = atan(t12);
t14 = B.*t11;
t15 = atan(t14);
t17 = delta+t13;
t18 = B.*t17;
t22 = -E.*(t14-t15);
t19 = atan(t18);
t25 = t14+t22;
t24 = -E.*(t18-t19);
t26 = atan(t25);
t27 = C.*t26;
t29 = t18+t24;
t28 = sin(t27);
t30 = atan(t29);
t31 = C.*t30;
t32 = sin(t31);
Xk = [Vypri+Ts.*((D.*t28+D.*t2.*t32)./Mv-Vxpri.*rpri);Vxpri+Ts.*(Abiaspri+Axpri-Vypri.*rpri);rpri-(Ts.*(D.*b.*t28-D.*a.*t2.*t32))./Iz;Psipri+Ts.*rpri;Abiaspri+Axpri;Rbiaspri;Abiaspri];
end
